[build]
builder = "NIXPACKS"

[deploy]
healthcheckPath = "/api/doc"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[[services]]
[services.variables]
PORT = "3001"
NODE_ENV = "production"
